// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using db.Data;

#nullable disable

namespace db.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("Dzivoklis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("DzivojamaPlatiba")
                        .HasColumnType("REAL");

                    b.Property<int>("IedzivotajuSkaits")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IstabuSkaits")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LodzijasPlatiba")
                        .HasColumnType("REAL");

                    b.Property<Guid>("MajaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Numurs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PilnaPlatiba")
                        .HasColumnType("REAL");

                    b.Property<int>("Stavs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UdensM3")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MajaId");

                    b.ToTable("Dzivokli", (string)null);
                });

            modelBuilder.Entity("DzivoklisIedzivotajs", b =>
                {
                    b.Property<Guid>("DzivokliId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IedzivotajiId")
                        .HasColumnType("TEXT");

                    b.HasKey("DzivokliId", "IedzivotajiId");

                    b.HasIndex("IedzivotajiId");

                    b.ToTable("DzivoklisIedzivotajs", (string)null);
                });

            modelBuilder.Entity("InvoiceService", b =>
                {
                    b.Property<Guid>("InvoicesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServicesId")
                        .HasColumnType("TEXT");

                    b.HasKey("InvoicesId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("InvoiceService");
                });

            modelBuilder.Entity("Maja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Iela")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Numurs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PastaIndekss")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pilseta")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valsts")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Majas", (string)null);
                });

            modelBuilder.Entity("db.Models.BillingInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ElectricityKwh")
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResidentsCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("WaterM3")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("BillingInputs");
                });

            modelBuilder.Entity("db.Models.Iedzivotajs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Epasts")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOwner")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("PersonasKods")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefons")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uzvards")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vards")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PersonasKods")
                        .IsUnique();

                    b.ToTable("Iedzivotaji", (string)null);
                });

            modelBuilder.Entity("db.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceIdentifier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LeaseholdId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("LeaseholdId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("db.Models.Leasehold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MajaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("MajaId");

                    b.ToTable("Leaseholds", (string)null);
                });

            modelBuilder.Entity("db.Models.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Formula")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LeaseholdId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Nodoklis")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nosaukums")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tarifs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LeaseholdId");

                    b.HasIndex("Nosaukums");

                    b.ToTable("Services", (string)null);
                });

            modelBuilder.Entity("db.Models.ServiceReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PreviousValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResidentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Usage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("ResidentId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceReadings");
                });

            modelBuilder.Entity("db.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IedzivotajsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IedzivotajsId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dzivoklis", b =>
                {
                    b.HasOne("Maja", "Maja")
                        .WithMany("Dzivokli")
                        .HasForeignKey("MajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maja");
                });

            modelBuilder.Entity("DzivoklisIedzivotajs", b =>
                {
                    b.HasOne("Dzivoklis", null)
                        .WithMany()
                        .HasForeignKey("DzivokliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db.Models.Iedzivotajs", null)
                        .WithMany()
                        .HasForeignKey("IedzivotajiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvoiceService", b =>
                {
                    b.HasOne("db.Models.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db.Models.Service", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("db.Models.BillingInput", b =>
                {
                    b.HasOne("Dzivoklis", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("db.Models.Invoice", b =>
                {
                    b.HasOne("Dzivoklis", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db.Models.Leasehold", null)
                        .WithMany("Invoices")
                        .HasForeignKey("LeaseholdId");

                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("db.Models.Leasehold", b =>
                {
                    b.HasOne("Dzivoklis", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Maja", "Maja")
                        .WithMany()
                        .HasForeignKey("MajaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Maja");
                });

            modelBuilder.Entity("db.Models.Service", b =>
                {
                    b.HasOne("db.Models.Leasehold", null)
                        .WithMany("Services")
                        .HasForeignKey("LeaseholdId");
                });

            modelBuilder.Entity("db.Models.ServiceReading", b =>
                {
                    b.HasOne("Dzivoklis", "Apartment")
                        .WithMany()
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db.Models.Iedzivotajs", "Resident")
                        .WithMany()
                        .HasForeignKey("ResidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("db.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("Resident");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("db.Models.User", b =>
                {
                    b.HasOne("db.Models.Iedzivotajs", "Iedzivotajs")
                        .WithOne("User")
                        .HasForeignKey("db.Models.User", "IedzivotajsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Iedzivotajs");
                });

            modelBuilder.Entity("Maja", b =>
                {
                    b.Navigation("Dzivokli");
                });

            modelBuilder.Entity("db.Models.Iedzivotajs", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("db.Models.Leasehold", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
